apiVersion: apps/v1
kind: Deployment
metadata:
  name: actor-app-backend
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: actor-app-backend
  template:
    metadata:
      labels:
        app: actor-app-backend
    spec:
      containers:
        - name: actor-app-backend
          image: demiapps.azurecr.io/actor-app-backend # Change this to your Docker image name
          ports:
            - containerPort: 80 # Change this to your Node.js application's port
          resources:
            requests:
              cpu: "100m" # 0.1 CPU cores
              memory: "128Mi" # 128MB
            limits:
              cpu: "500m" # 0.5 CPU cores
              memory: "512Mi" # 512MB
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5